from enum import Enum


class ContentOrigin(str, Enum):
    """
    Enum class for content visibility

    Attributes:
    -----------
    INITIAL_DATA : str
        Content is created from initial data.
    MANUALLY_CREATED : str
        Content is manually created.
    AI_GENERATED : str
        Content is generated by AI.
    INGESTED : str
        Content is ingested.
    SEARCH_QUERY : str
        Content is the text of a search query, angelegt vom Suchpfad selbst.
    """

    INITIAL_DATA = "initial_data"
    MANUALLY_CREATED = "manually_created"
    AI_GENERATED = "ai-generated"
    INGESTED = "ingested"
    SEARCH_QUERY = "search_query"


SEARCH_QUERY_AUTHOR = "system:suchanfrage"
"""
Autor, der an Statements aus Suchanfragen haengt - statt der suchenden Person.

Eine Suchanfrage ist keine Autorenleistung: sie faellt automatisch an, sobald
jemand das Suchfeld benutzt, und wer gesucht hat, geht aus dem Statement
niemand etwas an. Der Wert traegt absichtlich einen Doppelpunkt, damit er nicht
mit einer Keycloak-User-ID oder dem Dummy-Login kollidieren kann.

Verwendet in api/v1/search.py und api/v1/statement.py (addStatement mit
source=search_query). Statements aus dem ausdruecklichen Weg "Beitrag
ergaenzen" behalten die Person als Autor.
"""
