from enum import Enum


class ContentOrigin(str, Enum):
    """
    Enum class for content visibility

    Attributes:
    -----------
    INITIAL_DATA : str
        Content is created from initial data.
    MANUALLY_CREATED : str
        Content is manually created.
    AI_GENERATED : str
        Content is generated by AI.
    INGESTED : str
        Content is ingested.
    """

    INITIAL_DATA = "initial_data"
    MANUALLY_CREATED = "manually_created"
    AI_GENERATED = "ai-generated"
    INGESTED = "ingested"
