server {
    # Forwarding HTTP to HTTPS

    server_name test.contentgruen.de;
    listen 80;
    listen [::]:80;

    if ($host = test.contentgruen.de) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    # Challenge route for Let's Encrypt Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}

server {
    # HTTPS Server Config

    server_name test.contentgruen.de;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate /etc/letsencrypt/live/test.contentgruen.de/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/test.contentgruen.de/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # All routes to Frontend
    location / {
        proxy_pass http://127.0.0.1:3000;  # Frontend Docker Container
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Challenge route for Let's Encrypt Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }
}
